MCOL-520 - move mysql_upgrade

diff --git a/oam/install_scripts/post-mysqld-install b/oam/install_scripts/post-mysqld-install
--- a/oam/install_scripts/post-mysqld-install
+++ b/oam/install_scripts/post-mysqld-install
@@ -8,6 +8,10 @@ prefix=/usr/local
 installdir=$prefix/mariadb/columnstore
 rpmmode=install
 user=mysql
+
+password=" "
+pwprompt=
+
 if [ $EUID -ne 0 ]; then
 	USER=`whoami 2>/dev/null`
 	user=$USER
@@ -24,6 +28,8 @@ for arg in "$@"; do
 		prefix=`dirname $installdir`
 	elif [ `expr -- "$arg" : '--user='` -eq 7 ]; then
 		user="`echo $arg | awk -F= '{print $2}'`"
+	elif [ $(expr -- "$arg" : '--password=') -eq 11 ]; then
+		password="$(echo $arg | awk -F= '{print $2}')"
 	else
 		echo "post-mysqld-install: ignoring unknown argument: $arg" 1>&2
 	fi
@@ -67,6 +73,36 @@ fi
 
 # InfiniDB testing hook...
 test -x /usr/local/bin/idb-testing-mysql-pre-start && /usr/local/bin/idb-testing-mysql-pre-start $installdir/mysql
+
+if [ -x $installdir/mysql/mysql-Columnstore ]; then
+	# Restart in the same way that mysqld will be started normally.
+	$installdir/mysql/mysql-Columnstore stop >/dev/null 2>&1
+	sleep 2
+	$installdir/mysql/mysql-Columnstore start
+
+	sleep 5
+	
+	# Run MariaDB (mysql) upgrade script, if it exist
+	if [ -x $installdir/mysql/bin/mysql_upgrade ]; then
+		if [[ ${password} == " " ]]; then
+			$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf > $tmpdir/mysql_upgrade.log
+			if [ $? -ne 0 ]; then
+				echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
+				$installdir/mysql/mysql-Columnstore stop
+				sleep 2
+				exit 2;
+			fi
+		else
+			$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf --password=$password  > $tmpdir/mysql_upgrade.log
+			if [ $? -ne 0 ]; then
+				echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
+				$installdir/mysql/mysql-Columnstore stop
+				sleep 2
+				exit 2;
+			fi
+		fi
+	fi
+fi
 
 ### Don't give the user the notes, we'll fix them ourselves...
 $installdir/mysql/scripts/mysql_install_db --rpm --user=$user --defaults-extra-file=$installdir/mysql/my.cnf --basedir=$installdir/mysql >/dev/null
