update

diff --git a/oam/install_scripts/post-mysql-install b/oam/install_scripts/post-mysql-install
--- a/oam/install_scripts/post-mysql-install
+++ b/oam/install_scripts/post-mysql-install
@@ -9,16 +9,22 @@ checkForError() {
 	# check for password error
 	grep "ERROR 1045" /tmp/mysql_install.log > /tmp/error.check
 	if [ `cat /tmp/error.check | wc -c` -ne 0 ]; then
-		password=`$installdir/bin/getMySQLpw`
-		if [ $? -ne 0 ]; then
-			echo "MySQL Password missing or incorrect"
+		if test -f $HOME/.my.cnf ; then
+			password=`cat $HOME/.my.cnf | grep password | awk '{gsub(/^[ \t]+|[ \t]+$/,"");print $3}'
+			pwprompt="-p$password"
+		else
+			echo "MySQL Password missing or incorrect, check .my.cnf file"
 			rm -f /tmp/error.check
 			$installdir/mysql/mysql-Columnstore stop
 			sleep 2
-			exit 2;
+			exit 1;
 		fi
-		rm -f /tmp/error.check
-		exit 1;
+	else
+        	echo "MySQL access error"
+                rm -f /tmp/error.check
+                $installdir/mysql/mysql-Columnstore stop
+                sleep 2
+                exit 1;
 	fi
 
 	rm -f /tmp/error.check
