MCOL-520 - change to exit on invalid command line argument

diff --git a/oam/install_scripts/post-install b/oam/install_scripts/post-install
--- a/oam/install_scripts/post-install
+++ b/oam/install_scripts/post-install
@@ -28,7 +28,9 @@ for arg in "$@"; do
 	elif [ `expr -- "$arg" : '--plugin='` -eq 9 ]; then
 		plugin="`echo $arg | awk -F= '{print $2}'`"
 	else
-		echo "post-install: ignoring unknown argument: $arg" 1>&2
+		echo "post-install: invalid unknown argument: $arg" 1>&2
+		echo "exiting..."
+		exit 1
 	fi
 done
  
diff --git a/oam/install_scripts/pre-uninstall b/oam/install_scripts/pre-uninstall
--- a/oam/install_scripts/pre-uninstall
+++ b/oam/install_scripts/pre-uninstall
@@ -2,7 +2,7 @@
 #
 # $Id: post-uninstall 421 2007-04-05 15:46:55Z dhill $
 #
-# Post-uninstall steps for columnstore install
+# pre-uninstall steps for columnstore install
 
 prefix=/usr/local
 installdir=$prefix/mariadb/columnstore
@@ -26,7 +26,9 @@ for arg in "$@"; do
 	elif [ `expr -- "$arg" : '--quiet'` -eq 7 ]; then
 		quiet=1
 	else
-		echo "post-uninstall: ignoring unknown argument: $arg" 1>&2
+		echo "pre-install: invalid unknown argument: $arg" 1>&2
+		echo "exiting..."
+		exit 1
 	fi
 done
 
