MCOL-520 - move mysql_upgrade

diff --git a/oam/install_scripts/post-mysqld-install b/oam/install_scripts/post-mysqld-install
--- a/oam/install_scripts/post-mysqld-install
+++ b/oam/install_scripts/post-mysqld-install
@@ -77,38 +77,43 @@ fi
 # InfiniDB testing hook...
 test -x /usr/local/bin/idb-testing-mysql-pre-start && /usr/local/bin/idb-testing-mysql-pre-start $installdir/mysql
 
-if [ -x $installdir/mysql/mysql-Columnstore ]; then
-	# Restart in the same way that mysqld will be started normally.
-	$installdir/mysql/mysql-Columnstore stop >/dev/null 2>&1
-	sleep 2
-	$installdir/mysql/mysql-Columnstore start
+# If DB exist, run upgrade script if it exist
+if [ -d $installdir/mysql/db/calpontsys ]; then
 
-	sleep 5
-	
-	# Run MariaDB (mysql) upgrade script, if it exist
-	if [ -x $installdir/mysql/bin/mysql_upgrade ]; then
-		if [[ ${password} == " " ]]; then
-			$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf > $tmpdir/mysql_upgrade.log
-			if [ $? -ne 0 ]; then
-				echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
-				$installdir/mysql/mysql-Columnstore stop
-				sleep 2
-				exit 2;
-			fi
-		else
-			$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf --password=$password  > $tmpdir/mysql_upgrade.log
-			if [ $? -ne 0 ]; then
-				echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
-				$installdir/mysql/mysql-Columnstore stop
-				sleep 2
-				exit 2;
+	if [ -x $installdir/mysql/mysql-Columnstore ]; then
+		# Restart in the same way that mysqld will be started normally.
+		$installdir/mysql/mysql-Columnstore stop >/dev/null 2>&1
+		sleep 2
+		$installdir/mysql/mysql-Columnstore start
+
+		sleep 5
+		
+		# Run MariaDB (mysql) upgrade script, if it exist
+		if [ -x $installdir/mysql/bin/mysql_upgrade ]; then
+			echo "Running mysql_upgrade script"
+			if [[ ${password} == " " ]]; then
+				$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf > $tmpdir/mysql_upgrade.log
+				if [ $? -ne 0 ]; then
+					echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
+					$installdir/mysql/mysql-Columnstore stop
+					sleep 2
+					exit 2;
+				fi
+			else
+				$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf --password=$password  > $tmpdir/mysql_upgrade.log
+				if [ $? -ne 0 ]; then
+					echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
+					$installdir/mysql/mysql-Columnstore stop
+					sleep 2
+					exit 2;
+				fi
 			fi
 		fi
+		
+		# stop
+		$installdir/mysql/mysql-Columnstore stop
+		sleep 2
 	fi
-	
-	# stop
-	$installdir/mysql/mysql-Columnstore stop >/dev/null 2>&1
-	sleep 2
 fi
 
 ### Don't give the user the notes, we'll fix them ourselves...
