MCOL-520 - moved mysql_upgrade to post-mysql-install

diff --git a/oam/install_scripts/post-mysql-install b/oam/install_scripts/post-mysql-install
--- a/oam/install_scripts/post-mysql-install
+++ b/oam/install_scripts/post-mysql-install
@@ -44,7 +44,7 @@ checkForError() {
 prefix=/usr/local
 installdir=$prefix/mariadb/columnstore
 rpmmode=install
-password=
+password=" "
 pwprompt=
 for arg in "$@"; do
 	if [ $(expr -- "$arg" : '--prefix=') -eq 9 ]; then
@@ -57,6 +57,8 @@ for arg in "$@"; do
 		prefix=$(dirname $installdir)
 	elif [ $(expr -- "$arg" : '--tmpdir=') -eq 9 ]; then
 		tmpdir="$(echo $arg | awk -F= '{print $2}')"
+	elif [ $(expr -- "$arg" : '--password=') -eq 11 ]; then
+		password="$(echo $arg | awk -F= '{print $2}')"
 	else
 		echo "ignoring unknown argument: $arg" 1>&2
 	fi
@@ -103,6 +105,27 @@ if [ -x $installdir/mysql/mysql-Columnstore ]; then
 	$installdir/mysql/mysql-Columnstore start
 
 	sleep 5
+	
+	# Run MariaDB (mysql) upgrade script, if it exist
+	if [ -x $installdir/mysql/bin/mysql_upgrade ]; then
+		if [[ ${password} == " " ]]; then
+			$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf > $tmpdir/mysql_upgrade.log
+			if [ $? -ne 0 ]; then
+				echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
+				$installdir/mysql/mysql-Columnstore stop
+				sleep 2
+				exit 2;
+			fi
+		else
+			$installdir/mysql/bin/mysql_upgrade --defaults-file=$installdir/mysql/my.cnf --password=$password  > $tmpdir/mysql_upgrade.log
+			if [ $? -ne 0 ]; then
+				echo "ERROR: mysql_upgrade failure, check $tmpdir/mysql_upgrade.log"
+				$installdir/mysql/mysql-Columnstore stop
+				sleep 2
+				exit 2;
+			fi
+		fi
+	fi
 
 	# Install various Calpont stuff...
 	$installdir/mysql/install_calpont_mysql.sh  --installdir=$installdir --tmpdir=$tmpdir
